### ISSUE TITLE
Do you need an IDE...

### ISSUE THREAD

**Issue by ice1000** [thautwarm/Rem#1]
I know it's quite dynamic but we still can do highlighting and quick fixes..

**Comment by thautwarm** [comment]
You can you up, and I know you do can..  
However, it's too late for me to learn how to write an IDE like Intellij-Julia others... I guess that I don't have enough time to learn about Jetbrains plugins this year.

**Comment by ice1000** [comment]
Since I asked "DO YOU NEED" instead of "ANY PLAN OF CREATING", you know what I mean

**Comment by thautwarm** [comment]
I see, and I think I really need it, my dear. I finally don't have to write Python in many scenes...  
Are you planning to make one？:)

**Comment by ice1000** [comment]
> my dear

o(*////▽////*)q

A plugin with syntax highlight and very basic completion and module creation can be done in a day if your bnf is Grammar-Kit-capable (yet another parser generator)

**Comment by ice1000** [comment]
You may provide me a JB-style 32*32 icon for files and modules, seperately

**Comment by thautwarm** [comment]
[rem?](https://cn.bing.com/images/search?view=detailV2&ccid=Y2SXemCo&id=D2C50DA56B3200D327DAAC1B0F5BAA48FCB6E3C1&thid=OIP.Y2SXemCoHBDACQUcRpJOTQHaF_&mediaurl=http%3a%2f%2fpre13.deviantart.net%2ff23c%2fth%2fpre%2ff%2f2016%2f274%2fa%2f1%2frem_by_aryesmye-dajh2xj.png&exph=804&expw=994&q=rem+anime&simid=607995267667331886&selectedIndex=2&qpvt=rem+anime&ajaxhist=0) this one is ok?
...

**Comment by ice1000** [comment]
JB style.

Examples:
+ for module ![](https://raw.githubusercontent.com/covscript/covscript-intellij/master/res/icons/icon%402x.png)
+ for file (I didn't make a 32*32 one yet so only 16*16) ![](https://raw.githubusercontent.com/covscript/covscript-intellij/master/res/icons/csc.png)

![image](https://user-images.githubusercontent.com/16398479/37505388-a515b35a-291f-11e8-8aa5-141e6cd2d364.png)

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/37505396-b368ad2c-291f-11e8-85b5-be7377cd5bde.png)

**Comment by ice1000** [comment]
Not urgent but better to have one. I'm at work now and I'll do this at weekend

**Comment by thautwarm** [comment]
@ice1000 先上班了我的爱

**Comment by ice1000** [comment]
我也在上班啊 = =

**Comment by ice1000** [comment]
你哪来那么多issue。。关这两个的时间间隔也太长了。。

**Comment by thautwarm** [comment]
忘关了不行？:(

**Comment by ice1000** [comment]
没有，我那个吐槽的表情是笑眯眯的

**Comment by ice1000** [comment]
你这么严肃我好紧张啊QAQ

**Comment by thautwarm** [comment]
@ice1000 你可以理解为月经期间人烦躁。。

**Comment by ice1000** [comment]
那我是不是应该疯狂撒娇来让你心情变好丫
 ![](https://gss0.baidu.com/94o3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/7a899e510fb30f240aed4d7dc395d143ad4b035c.jpg)
